# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_client.models.ticket import Ticket

class TestTicket(unittest.TestCase):
    """Ticket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ticket:
        """Test Ticket
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ticket`
        """
        model = Ticket()
        if include_optional:
            return Ticket(
                id = 56,
                number = '',
                department_id = 56,
                department_email_id = 56,
                brand_id = 56,
                channel_id = 56,
                user_id = 56,
                status_id = 56,
                priority_id = 56,
                sla_plan_id = 56,
                subject = '',
                due_time = 56,
                resolved_time = 56,
                cc = [
                    ''
                    ],
                locked = 56,
                merged = 56,
                internal = 56,
                created_at = 56,
                updated_at = 56,
                deleted_at = 56,
                frontend_url = '',
                operator_url = '',
                token = '',
                department = supportpal_client.models.department.Department(
                    id = 56, 
                    name = '', 
                    description = '', 
                    order = 56, 
                    parent = 56, 
                    public = 56, 
                    created_at = 56, 
                    updated_at = 56, ),
                channel = supportpal_client.models.channel.Channel(
                    id = 56, 
                    name = '', 
                    enabled = 56, 
                    created_at = 56, 
                    updated_at = 56, ),
                user = supportpal_client.models.user_summary.UserSummary(
                    id = 56, 
                    firstname = '', 
                    lastname = '', 
                    email = '', 
                    email_verified = 56, 
                    organisation_id = 56, 
                    organisation_access_level = 56, 
                    country = '', 
                    language_code = '', 
                    timezone = '', 
                    avatar = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    formatted_name = '', ),
                status = supportpal_client.models.ticket_status.TicketStatus(
                    id = 56, 
                    name = '', 
                    colour = '', 
                    auto_close = 56, 
                    order = 56, 
                    created_at = 56, 
                    updated_at = 56, ),
                priority = supportpal_client.models.priority.Priority(
                    id = 56, 
                    name = '', 
                    colour = '', 
                    order = 56, 
                    created_at = 56, 
                    updated_at = 56, ),
                slaplan = None
            )
        else:
            return Ticket(
        )
        """

    def testTicket(self):
        """Test Ticket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
