# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_client.models.feedback_form import FeedbackForm

class TestFeedbackForm(unittest.TestCase):
    """FeedbackForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedbackForm:
        """Test FeedbackForm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedbackForm`
        """
        model = FeedbackForm()
        if include_optional:
            return FeedbackForm(
                id = 56,
                name = '',
                description = '',
                email_template_id = 56,
                condition_group_type = 56,
                expiry_time = 56,
                time_after_resolved = 56,
                fields = [
                    None
                    ],
                translations = [
                    None
                    ],
                created_at = 56,
                updated_at = 56
            )
        else:
            return FeedbackForm(
        )
        """

    def testFeedbackForm(self):
        """Test FeedbackForm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
