# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_client.models.ticket_list_response import TicketListResponse

class TestTicketListResponse(unittest.TestCase):
    """TicketListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TicketListResponse:
        """Test TicketListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TicketListResponse`
        """
        model = TicketListResponse()
        if include_optional:
            return TicketListResponse(
                status = '',
                message = '',
                count = 56,
                data = [
                    supportpal_client.models.ticket.Ticket(
                        id = 56, 
                        number = '', 
                        department_id = 56, 
                        department_email_id = 56, 
                        brand_id = 56, 
                        channel_id = 56, 
                        user_id = 56, 
                        status_id = 56, 
                        priority_id = 56, 
                        sla_plan_id = 56, 
                        subject = '', 
                        due_time = 56, 
                        resolved_time = 56, 
                        cc = [
                            ''
                            ], 
                        locked = 56, 
                        merged = 56, 
                        internal = 56, 
                        created_at = 56, 
                        updated_at = 56, 
                        deleted_at = 56, 
                        frontend_url = '', 
                        operator_url = '', 
                        token = '', 
                        department = null, 
                        channel = null, 
                        user = null, 
                        status = null, 
                        priority = null, 
                        slaplan = supportpal_client.models.slaplan.slaplan(), )
                    ]
            )
        else:
            return TicketListResponse(
        )
        """

    def testTicketListResponse(self):
        """Test TicketListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
