# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_client.api.feedback_api import FeedbackApi


class TestFeedbackApi(unittest.TestCase):
    """FeedbackApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeedbackApi()

    def tearDown(self) -> None:
        pass

    def test_get_feedback(self) -> None:
        """Test case for get_feedback

        Get feedback by ID
        """
        pass

    def test_list_feedback(self) -> None:
        """Test case for list_feedback

        List ticket feedback
        """
        pass


if __name__ == '__main__':
    unittest.main()
