# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_client.models.department import Department

class TestDepartment(unittest.TestCase):
    """Department unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Department:
        """Test Department
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Department`
        """
        model = Department()
        if include_optional:
            return Department(
                id = 56,
                name = '',
                description = '',
                order = 56,
                parent = 56,
                public = 56,
                created_at = 56,
                updated_at = 56
            )
        else:
            return Department(
        )
        """

    def testDepartment(self):
        """Test Department"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
