# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_api_client.api.operator_api import OperatorApi


class TestOperatorApi(unittest.TestCase):
    """OperatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OperatorApi()

    def tearDown(self) -> None:
        pass

    def test_get_operator(self) -> None:
        """Test case for get_operator

        Get operator by ID
        """
        pass

    def test_list_operators(self) -> None:
        """Test case for list_operators

        List operators
        """
        pass


if __name__ == '__main__':
    unittest.main()
