# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_api_client.models.message import Message

class TestMessage(unittest.TestCase):
    """Message unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Message:
        """Test Message
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Message`
        """
        model = Message()
        if include_optional:
            return Message(
                id = 56,
                ticket_id = 56,
                channel_id = 56,
                user_id = 56,
                user_ip_address = '',
                by = 56,
                type = 56,
                text = '',
                is_draft = 56,
                social_id = '',
                created_at = 56,
                updated_at = 56,
                user = supportpal_api_client.models.user_summary.UserSummary(
                    id = 56, 
                    firstname = '', 
                    lastname = '', 
                    email = '', 
                    email_verified = 56, 
                    organisation_id = 56, 
                    organisation_access_level = 56, 
                    country = '', 
                    language_code = '', 
                    timezone = '', 
                    avatar = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    formatted_name = '', )
            )
        else:
            return Message(
        )
        """

    def testMessage(self):
        """Test Message"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
