# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_api_client.api.ticket_api import TicketApi


class TestTicketApi(unittest.TestCase):
    """TicketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TicketApi()

    def tearDown(self) -> None:
        pass

    def test_get_ticket(self) -> None:
        """Test case for get_ticket

        Get ticket by ID
        """
        pass

    def test_list_tickets(self) -> None:
        """Test case for list_tickets

        List tickets
        """
        pass


if __name__ == '__main__':
    unittest.main()
