# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_client.models.feedback_list_response import FeedbackListResponse

class TestFeedbackListResponse(unittest.TestCase):
    """FeedbackListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedbackListResponse:
        """Test FeedbackListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedbackListResponse`
        """
        model = FeedbackListResponse()
        if include_optional:
            return FeedbackListResponse(
                status = '',
                message = '',
                count = 56,
                data = [
                    supportpal_client.models.feedback.Feedback(
                        id = 56, 
                        ticket_id = 56, 
                        form_id = 56, 
                        rating = 56, 
                        fields_answered = 56, 
                        token = '', 
                        expiry_time = 56, 
                        values = [
                            None
                            ], 
                        form = null, 
                        created_at = 56, 
                        updated_at = 56, )
                    ]
            )
        else:
            return FeedbackListResponse(
        )
        """

    def testFeedbackListResponse(self):
        """Test FeedbackListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
