# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_api_client.models.message_list_response import MessageListResponse

class TestMessageListResponse(unittest.TestCase):
    """MessageListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageListResponse:
        """Test MessageListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageListResponse`
        """
        model = MessageListResponse()
        if include_optional:
            return MessageListResponse(
                status = '',
                message = '',
                count = 56,
                data = [
                    supportpal_api_client.models.message.Message(
                        id = 56, 
                        ticket_id = 56, 
                        channel_id = 56, 
                        user_id = 56, 
                        user_ip_address = '', 
                        by = 56, 
                        type = 56, 
                        text = '', 
                        is_draft = 56, 
                        social_id = '', 
                        created_at = 56, 
                        updated_at = 56, 
                        user = null, )
                    ]
            )
        else:
            return MessageListResponse(
        )
        """

    def testMessageListResponse(self):
        """Test MessageListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
