# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supportpal_client.api.message_api import MessageApi


class TestMessageApi(unittest.TestCase):
    """MessageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageApi()

    def tearDown(self) -> None:
        pass

    def test_get_message(self) -> None:
        """Test case for get_message

        Get message by ID
        """
        pass

    def test_list_messages(self) -> None:
        """Test case for list_messages

        List messages for a ticket
        """
        pass


if __name__ == '__main__':
    unittest.main()
