# coding: utf-8

# flake8: noqa
"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from supportpal_client.models.channel import Channel
from supportpal_client.models.department import Department
from supportpal_client.models.feedback import Feedback
from supportpal_client.models.feedback_form import FeedbackForm
from supportpal_client.models.feedback_list_response import FeedbackListResponse
from supportpal_client.models.message import Message
from supportpal_client.models.message_list_response import MessageListResponse
from supportpal_client.models.message_response import MessageResponse
from supportpal_client.models.operator import Operator
from supportpal_client.models.operator_list_response import OperatorListResponse
from supportpal_client.models.operator_response import OperatorResponse
from supportpal_client.models.priority import Priority
from supportpal_client.models.ticket import Ticket
from supportpal_client.models.ticket_cc import TicketCc
from supportpal_client.models.ticket_list_response import TicketListResponse
from supportpal_client.models.ticket_response import TicketResponse
from supportpal_client.models.ticket_status import TicketStatus
from supportpal_client.models.user_summary import UserSummary

