# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from supportpal_client.models.feedback_form import FeedbackForm
from typing import Optional, Set
from typing_extensions import Self

class Feedback(BaseModel):
    """
    Feedback
    """ # noqa: E501
    id: Optional[StrictInt] = None
    ticket_id: Optional[StrictInt] = None
    form_id: Optional[StrictInt] = None
    rating: Optional[StrictInt] = Field(default=None, description="Customer satisfaction rating: null = not yet responded, 0 = bad, 1 = good, 2 = neutral")
    fields_answered: Optional[StrictInt] = None
    token: Optional[StrictStr] = None
    expiry_time: Optional[StrictInt] = None
    values: Optional[List[Dict[str, Any]]] = None
    form: Optional[FeedbackForm] = None
    created_at: Optional[StrictInt] = None
    updated_at: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "ticket_id", "form_id", "rating", "fields_answered", "token", "expiry_time", "values", "form", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Feedback from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of form
        if self.form:
            _dict['form'] = self.form.to_dict()
        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict['rating'] = None

        # set to None if form (nullable) is None
        # and model_fields_set contains the field
        if self.form is None and "form" in self.model_fields_set:
            _dict['form'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Feedback from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "ticket_id": obj.get("ticket_id"),
            "form_id": obj.get("form_id"),
            "rating": obj.get("rating"),
            "fields_answered": obj.get("fields_answered"),
            "token": obj.get("token"),
            "expiry_time": obj.get("expiry_time"),
            "values": obj.get("values"),
            "form": FeedbackForm.from_dict(obj["form"]) if obj.get("form") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


