# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FeedbackForm(BaseModel):
    """
    FeedbackForm
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    email_template_id: Optional[StrictInt] = None
    condition_group_type: Optional[StrictInt] = None
    expiry_time: Optional[StrictInt] = None
    time_after_resolved: Optional[StrictInt] = None
    fields: Optional[List[Dict[str, Any]]] = None
    translations: Optional[List[Dict[str, Any]]] = None
    created_at: Optional[StrictInt] = None
    updated_at: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "email_template_id", "condition_group_type", "expiry_time", "time_after_resolved", "fields", "translations", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeedbackForm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if email_template_id (nullable) is None
        # and model_fields_set contains the field
        if self.email_template_id is None and "email_template_id" in self.model_fields_set:
            _dict['email_template_id'] = None

        # set to None if expiry_time (nullable) is None
        # and model_fields_set contains the field
        if self.expiry_time is None and "expiry_time" in self.model_fields_set:
            _dict['expiry_time'] = None

        # set to None if time_after_resolved (nullable) is None
        # and model_fields_set contains the field
        if self.time_after_resolved is None and "time_after_resolved" in self.model_fields_set:
            _dict['time_after_resolved'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeedbackForm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "email_template_id": obj.get("email_template_id"),
            "condition_group_type": obj.get("condition_group_type"),
            "expiry_time": obj.get("expiry_time"),
            "time_after_resolved": obj.get("time_after_resolved"),
            "fields": obj.get("fields"),
            "translations": obj.get("translations"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


