# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from supportpal_client.models.user_summary import UserSummary
from typing import Optional, Set
from typing_extensions import Self

class Message(BaseModel):
    """
    Message
    """ # noqa: E501
    id: Optional[StrictInt] = None
    ticket_id: Optional[StrictInt] = None
    channel_id: Optional[StrictInt] = None
    user_id: Optional[StrictInt] = None
    user_ip_address: Optional[StrictStr] = None
    by: Optional[StrictInt] = Field(default=None, description="Author type: 0 = operator, 1 = user (customer)")
    type: Optional[StrictInt] = Field(default=None, description="Message type: 0 = message, 1 = internal note")
    text: Optional[StrictStr] = None
    is_draft: Optional[StrictInt] = None
    social_id: Optional[StrictStr] = None
    created_at: Optional[StrictInt] = None
    updated_at: Optional[StrictInt] = None
    user: Optional[UserSummary] = None
    __properties: ClassVar[List[str]] = ["id", "ticket_id", "channel_id", "user_id", "user_ip_address", "by", "type", "text", "is_draft", "social_id", "created_at", "updated_at", "user"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Message from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # set to None if user_ip_address (nullable) is None
        # and model_fields_set contains the field
        if self.user_ip_address is None and "user_ip_address" in self.model_fields_set:
            _dict['user_ip_address'] = None

        # set to None if social_id (nullable) is None
        # and model_fields_set contains the field
        if self.social_id is None and "social_id" in self.model_fields_set:
            _dict['social_id'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Message from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "ticket_id": obj.get("ticket_id"),
            "channel_id": obj.get("channel_id"),
            "user_id": obj.get("user_id"),
            "user_ip_address": obj.get("user_ip_address"),
            "by": obj.get("by"),
            "type": obj.get("type"),
            "text": obj.get("text"),
            "is_draft": obj.get("is_draft"),
            "social_id": obj.get("social_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "user": UserSummary.from_dict(obj["user"]) if obj.get("user") is not None else None
        })
        return _obj


