# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from supportpal_client.models.channel import Channel
from supportpal_client.models.department import Department
from supportpal_client.models.priority import Priority
from supportpal_client.models.ticket_cc import TicketCc
from supportpal_client.models.ticket_status import TicketStatus
from supportpal_client.models.user_summary import UserSummary
from typing import Optional, Set
from typing_extensions import Self

class Ticket(BaseModel):
    """
    Ticket
    """ # noqa: E501
    id: Optional[StrictInt] = None
    number: Optional[StrictStr] = None
    department_id: Optional[StrictInt] = None
    department_email_id: Optional[StrictInt] = None
    brand_id: Optional[StrictInt] = None
    channel_id: Optional[StrictInt] = None
    user_id: Optional[StrictInt] = None
    status_id: Optional[StrictInt] = None
    priority_id: Optional[StrictInt] = None
    sla_plan_id: Optional[StrictInt] = None
    subject: Optional[StrictStr] = None
    due_time: Optional[StrictInt] = None
    resolved_time: Optional[StrictInt] = None
    cc: Optional[TicketCc] = None
    locked: Optional[StrictInt] = None
    merged: Optional[StrictInt] = None
    internal: Optional[StrictInt] = None
    created_at: Optional[StrictInt] = None
    updated_at: Optional[StrictInt] = None
    deleted_at: Optional[StrictInt] = None
    frontend_url: Optional[StrictStr] = None
    operator_url: Optional[StrictStr] = None
    token: Optional[StrictStr] = None
    department: Optional[Department] = None
    channel: Optional[Channel] = None
    user: Optional[UserSummary] = None
    status: Optional[TicketStatus] = None
    priority: Optional[Priority] = None
    slaplan: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "number", "department_id", "department_email_id", "brand_id", "channel_id", "user_id", "status_id", "priority_id", "sla_plan_id", "subject", "due_time", "resolved_time", "cc", "locked", "merged", "internal", "created_at", "updated_at", "deleted_at", "frontend_url", "operator_url", "token", "department", "channel", "user", "status", "priority", "slaplan"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Ticket from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cc
        if self.cc:
            _dict['cc'] = self.cc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of department
        if self.department:
            _dict['department'] = self.department.to_dict()
        # override the default output from pydantic by calling `to_dict()` of channel
        if self.channel:
            _dict['channel'] = self.channel.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of priority
        if self.priority:
            _dict['priority'] = self.priority.to_dict()
        # set to None if department_email_id (nullable) is None
        # and model_fields_set contains the field
        if self.department_email_id is None and "department_email_id" in self.model_fields_set:
            _dict['department_email_id'] = None

        # set to None if sla_plan_id (nullable) is None
        # and model_fields_set contains the field
        if self.sla_plan_id is None and "sla_plan_id" in self.model_fields_set:
            _dict['sla_plan_id'] = None

        # set to None if due_time (nullable) is None
        # and model_fields_set contains the field
        if self.due_time is None and "due_time" in self.model_fields_set:
            _dict['due_time'] = None

        # set to None if resolved_time (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_time is None and "resolved_time" in self.model_fields_set:
            _dict['resolved_time'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        # set to None if department (nullable) is None
        # and model_fields_set contains the field
        if self.department is None and "department" in self.model_fields_set:
            _dict['department'] = None

        # set to None if channel (nullable) is None
        # and model_fields_set contains the field
        if self.channel is None and "channel" in self.model_fields_set:
            _dict['channel'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if slaplan (nullable) is None
        # and model_fields_set contains the field
        if self.slaplan is None and "slaplan" in self.model_fields_set:
            _dict['slaplan'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Ticket from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "number": obj.get("number"),
            "department_id": obj.get("department_id"),
            "department_email_id": obj.get("department_email_id"),
            "brand_id": obj.get("brand_id"),
            "channel_id": obj.get("channel_id"),
            "user_id": obj.get("user_id"),
            "status_id": obj.get("status_id"),
            "priority_id": obj.get("priority_id"),
            "sla_plan_id": obj.get("sla_plan_id"),
            "subject": obj.get("subject"),
            "due_time": obj.get("due_time"),
            "resolved_time": obj.get("resolved_time"),
            "cc": TicketCc.from_dict(obj["cc"]) if obj.get("cc") is not None else None,
            "locked": obj.get("locked"),
            "merged": obj.get("merged"),
            "internal": obj.get("internal"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "deleted_at": obj.get("deleted_at"),
            "frontend_url": obj.get("frontend_url"),
            "operator_url": obj.get("operator_url"),
            "token": obj.get("token"),
            "department": Department.from_dict(obj["department"]) if obj.get("department") is not None else None,
            "channel": Channel.from_dict(obj["channel"]) if obj.get("channel") is not None else None,
            "user": UserSummary.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "status": TicketStatus.from_dict(obj["status"]) if obj.get("status") is not None else None,
            "priority": Priority.from_dict(obj["priority"]) if obj.get("priority") is not None else None,
            "slaplan": obj.get("slaplan")
        })
        return _obj


