# coding: utf-8

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserSummary(BaseModel):
    """
    A user (customer) account embedded in ticket and message responses
    """ # noqa: E501
    id: Optional[StrictInt] = None
    firstname: Optional[StrictStr] = None
    lastname: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    email_verified: Optional[StrictInt] = None
    organisation_id: Optional[StrictInt] = None
    organisation_access_level: Optional[StrictInt] = None
    country: Optional[StrictStr] = None
    language_code: Optional[StrictStr] = None
    timezone: Optional[StrictStr] = None
    avatar: Optional[StrictStr] = None
    created_at: Optional[StrictInt] = None
    updated_at: Optional[StrictInt] = None
    formatted_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "firstname", "lastname", "email", "email_verified", "organisation_id", "organisation_access_level", "country", "language_code", "timezone", "avatar", "created_at", "updated_at", "formatted_name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if organisation_id (nullable) is None
        # and model_fields_set contains the field
        if self.organisation_id is None and "organisation_id" in self.model_fields_set:
            _dict['organisation_id'] = None

        # set to None if organisation_access_level (nullable) is None
        # and model_fields_set contains the field
        if self.organisation_access_level is None and "organisation_access_level" in self.model_fields_set:
            _dict['organisation_access_level'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if language_code (nullable) is None
        # and model_fields_set contains the field
        if self.language_code is None and "language_code" in self.model_fields_set:
            _dict['language_code'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if avatar (nullable) is None
        # and model_fields_set contains the field
        if self.avatar is None and "avatar" in self.model_fields_set:
            _dict['avatar'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "firstname": obj.get("firstname"),
            "lastname": obj.get("lastname"),
            "email": obj.get("email"),
            "email_verified": obj.get("email_verified"),
            "organisation_id": obj.get("organisation_id"),
            "organisation_access_level": obj.get("organisation_access_level"),
            "country": obj.get("country"),
            "language_code": obj.get("language_code"),
            "timezone": obj.get("timezone"),
            "avatar": obj.get("avatar"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "formatted_name": obj.get("formatted_name")
        })
        return _obj


