"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from supportpal_client.models.ticket_list_response import TicketListResponse
from supportpal_client.models.ticket_response import TicketResponse

from supportpal_client.api_client import ApiClient, RequestSerialized
from supportpal_client.api_response import ApiResponse
from supportpal_client.rest import RESTResponseType


class TicketApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_ticket(
        self,
        id: StrictInt,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TicketResponse:
        """Get ticket by ID


        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ticket_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TicketResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_ticket_with_http_info(
        self,
        id: StrictInt,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TicketResponse]:
        """Get ticket by ID


        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ticket_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TicketResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_ticket_without_preload_content(
        self,
        id: StrictInt,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get ticket by ID


        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ticket_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TicketResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_ticket_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BasicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/ticket/ticket/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_tickets(
        self,
        department: Annotated[Optional[StrictStr], Field(description="Filter by department ID(s), comma delimited e.g. 1,2,3")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status ID(s), comma delimited e.g. 1,2,3")] = None,
        assigned: Annotated[Optional[StrictStr], Field(description="Filter by assigned operator ID(s), use -1 for unassigned tickets")] = None,
        start: Annotated[Optional[StrictInt], Field(description="The first result offset (1-indexed)")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The number of results to fetch per page")] = None,
        order_column: Optional[StrictStr] = None,
        order_direction: Optional[StrictStr] = None,
        created_at_min: Annotated[Optional[StrictInt], Field(description="Filter tickets created since this UNIX timestamp")] = None,
        created_at_max: Annotated[Optional[StrictInt], Field(description="Filter tickets created before this UNIX timestamp")] = None,
        updated_at_min: Annotated[Optional[StrictInt], Field(description="Filter tickets updated since this UNIX timestamp")] = None,
        updated_at_max: Annotated[Optional[StrictInt], Field(description="Filter tickets updated before this UNIX timestamp")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TicketListResponse:
        """List tickets


        :param department: Filter by department ID(s), comma delimited e.g. 1,2,3
        :type department: str
        :param status: Filter by status ID(s), comma delimited e.g. 1,2,3
        :type status: str
        :param assigned: Filter by assigned operator ID(s), use -1 for unassigned tickets
        :type assigned: str
        :param start: The first result offset (1-indexed)
        :type start: int
        :param limit: The number of results to fetch per page
        :type limit: int
        :param order_column:
        :type order_column: str
        :param order_direction:
        :type order_direction: str
        :param created_at_min: Filter tickets created since this UNIX timestamp
        :type created_at_min: int
        :param created_at_max: Filter tickets created before this UNIX timestamp
        :type created_at_max: int
        :param updated_at_min: Filter tickets updated since this UNIX timestamp
        :type updated_at_min: int
        :param updated_at_max: Filter tickets updated before this UNIX timestamp
        :type updated_at_max: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_tickets_serialize(
            department=department,
            status=status,
            assigned=assigned,
            start=start,
            limit=limit,
            order_column=order_column,
            order_direction=order_direction,
            created_at_min=created_at_min,
            created_at_max=created_at_max,
            updated_at_min=updated_at_min,
            updated_at_max=updated_at_max,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TicketListResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_tickets_with_http_info(
        self,
        department: Annotated[Optional[StrictStr], Field(description="Filter by department ID(s), comma delimited e.g. 1,2,3")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status ID(s), comma delimited e.g. 1,2,3")] = None,
        assigned: Annotated[Optional[StrictStr], Field(description="Filter by assigned operator ID(s), use -1 for unassigned tickets")] = None,
        start: Annotated[Optional[StrictInt], Field(description="The first result offset (1-indexed)")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The number of results to fetch per page")] = None,
        order_column: Optional[StrictStr] = None,
        order_direction: Optional[StrictStr] = None,
        created_at_min: Annotated[Optional[StrictInt], Field(description="Filter tickets created since this UNIX timestamp")] = None,
        created_at_max: Annotated[Optional[StrictInt], Field(description="Filter tickets created before this UNIX timestamp")] = None,
        updated_at_min: Annotated[Optional[StrictInt], Field(description="Filter tickets updated since this UNIX timestamp")] = None,
        updated_at_max: Annotated[Optional[StrictInt], Field(description="Filter tickets updated before this UNIX timestamp")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TicketListResponse]:
        """List tickets


        :param department: Filter by department ID(s), comma delimited e.g. 1,2,3
        :type department: str
        :param status: Filter by status ID(s), comma delimited e.g. 1,2,3
        :type status: str
        :param assigned: Filter by assigned operator ID(s), use -1 for unassigned tickets
        :type assigned: str
        :param start: The first result offset (1-indexed)
        :type start: int
        :param limit: The number of results to fetch per page
        :type limit: int
        :param order_column:
        :type order_column: str
        :param order_direction:
        :type order_direction: str
        :param created_at_min: Filter tickets created since this UNIX timestamp
        :type created_at_min: int
        :param created_at_max: Filter tickets created before this UNIX timestamp
        :type created_at_max: int
        :param updated_at_min: Filter tickets updated since this UNIX timestamp
        :type updated_at_min: int
        :param updated_at_max: Filter tickets updated before this UNIX timestamp
        :type updated_at_max: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_tickets_serialize(
            department=department,
            status=status,
            assigned=assigned,
            start=start,
            limit=limit,
            order_column=order_column,
            order_direction=order_direction,
            created_at_min=created_at_min,
            created_at_max=created_at_max,
            updated_at_min=updated_at_min,
            updated_at_max=updated_at_max,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TicketListResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_tickets_without_preload_content(
        self,
        department: Annotated[Optional[StrictStr], Field(description="Filter by department ID(s), comma delimited e.g. 1,2,3")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status ID(s), comma delimited e.g. 1,2,3")] = None,
        assigned: Annotated[Optional[StrictStr], Field(description="Filter by assigned operator ID(s), use -1 for unassigned tickets")] = None,
        start: Annotated[Optional[StrictInt], Field(description="The first result offset (1-indexed)")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The number of results to fetch per page")] = None,
        order_column: Optional[StrictStr] = None,
        order_direction: Optional[StrictStr] = None,
        created_at_min: Annotated[Optional[StrictInt], Field(description="Filter tickets created since this UNIX timestamp")] = None,
        created_at_max: Annotated[Optional[StrictInt], Field(description="Filter tickets created before this UNIX timestamp")] = None,
        updated_at_min: Annotated[Optional[StrictInt], Field(description="Filter tickets updated since this UNIX timestamp")] = None,
        updated_at_max: Annotated[Optional[StrictInt], Field(description="Filter tickets updated before this UNIX timestamp")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List tickets


        :param department: Filter by department ID(s), comma delimited e.g. 1,2,3
        :type department: str
        :param status: Filter by status ID(s), comma delimited e.g. 1,2,3
        :type status: str
        :param assigned: Filter by assigned operator ID(s), use -1 for unassigned tickets
        :type assigned: str
        :param start: The first result offset (1-indexed)
        :type start: int
        :param limit: The number of results to fetch per page
        :type limit: int
        :param order_column:
        :type order_column: str
        :param order_direction:
        :type order_direction: str
        :param created_at_min: Filter tickets created since this UNIX timestamp
        :type created_at_min: int
        :param created_at_max: Filter tickets created before this UNIX timestamp
        :type created_at_max: int
        :param updated_at_min: Filter tickets updated since this UNIX timestamp
        :type updated_at_min: int
        :param updated_at_max: Filter tickets updated before this UNIX timestamp
        :type updated_at_max: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_tickets_serialize(
            department=department,
            status=status,
            assigned=assigned,
            start=start,
            limit=limit,
            order_column=order_column,
            order_direction=order_direction,
            created_at_min=created_at_min,
            created_at_max=created_at_max,
            updated_at_min=updated_at_min,
            updated_at_max=updated_at_max,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TicketListResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_tickets_serialize(
        self,
        department,
        status,
        assigned,
        start,
        limit,
        order_column,
        order_direction,
        created_at_min,
        created_at_max,
        updated_at_min,
        updated_at_max,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if department is not None:
            
            _query_params.append(('department', department))
            
        if status is not None:
            
            _query_params.append(('status', status))
            
        if assigned is not None:
            
            _query_params.append(('assigned', assigned))
            
        if start is not None:
            
            _query_params.append(('start', start))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if order_column is not None:
            
            _query_params.append(('order_column', order_column))
            
        if order_direction is not None:
            
            _query_params.append(('order_direction', order_direction))
            
        if created_at_min is not None:
            
            _query_params.append(('created_at_min', created_at_min))
            
        if created_at_max is not None:
            
            _query_params.append(('created_at_max', created_at_max))
            
        if updated_at_min is not None:
            
            _query_params.append(('updated_at_min', updated_at_min))
            
        if updated_at_max is not None:
            
            _query_params.append(('updated_at_max', updated_at_max))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BasicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/ticket/ticket',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


