# coding: utf-8

# flake8: noqa

"""
    SupportPal REST API

    API for accessing SupportPal tickets, messages, operators, and feedback for AI-powered ticket analysis.

    The version of the OpenAPI document: 1.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.3"

# Define package exports
__all__ = [
    "FeedbackApi",
    "MessageApi",
    "OperatorApi",
    "TicketApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Channel",
    "Department",
    "Feedback",
    "FeedbackForm",
    "FeedbackListResponse",
    "Message",
    "MessageListResponse",
    "MessageResponse",
    "Operator",
    "OperatorListResponse",
    "OperatorResponse",
    "Priority",
    "Ticket",
    "TicketCc",
    "TicketListResponse",
    "TicketResponse",
    "TicketStatus",
    "UserSummary",
]

# import apis into sdk package
from supportpal_client.api.feedback_api import FeedbackApi as FeedbackApi
from supportpal_client.api.message_api import MessageApi as MessageApi
from supportpal_client.api.operator_api import OperatorApi as OperatorApi
from supportpal_client.api.ticket_api import TicketApi as TicketApi

# import ApiClient
from supportpal_client.api_response import ApiResponse as ApiResponse
from supportpal_client.api_client import ApiClient as ApiClient
from supportpal_client.configuration import Configuration as Configuration
from supportpal_client.exceptions import OpenApiException as OpenApiException
from supportpal_client.exceptions import ApiTypeError as ApiTypeError
from supportpal_client.exceptions import ApiValueError as ApiValueError
from supportpal_client.exceptions import ApiKeyError as ApiKeyError
from supportpal_client.exceptions import ApiAttributeError as ApiAttributeError
from supportpal_client.exceptions import ApiException as ApiException

# import models into sdk package
from supportpal_client.models.channel import Channel as Channel
from supportpal_client.models.department import Department as Department
from supportpal_client.models.feedback import Feedback as Feedback
from supportpal_client.models.feedback_form import FeedbackForm as FeedbackForm
from supportpal_client.models.feedback_list_response import FeedbackListResponse as FeedbackListResponse
from supportpal_client.models.message import Message as Message
from supportpal_client.models.message_list_response import MessageListResponse as MessageListResponse
from supportpal_client.models.message_response import MessageResponse as MessageResponse
from supportpal_client.models.operator import Operator as Operator
from supportpal_client.models.operator_list_response import OperatorListResponse as OperatorListResponse
from supportpal_client.models.operator_response import OperatorResponse as OperatorResponse
from supportpal_client.models.priority import Priority as Priority
from supportpal_client.models.ticket import Ticket as Ticket
from supportpal_client.models.ticket_cc import TicketCc as TicketCc
from supportpal_client.models.ticket_list_response import TicketListResponse as TicketListResponse
from supportpal_client.models.ticket_response import TicketResponse as TicketResponse
from supportpal_client.models.ticket_status import TicketStatus as TicketStatus
from supportpal_client.models.user_summary import UserSummary as UserSummary
